version: "3.7"
services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: password
      MB_DB_HOST: db
      JAVA_TIMEZONE: Asia/Tokyo
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: metabase
        POSTGRES_PASSWORD: password
