version: "3.7"
services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
      - "9229:9229"
    command: "nodemon --inspect=0.0.0.0:9229 --watch src"
    init: true
