version: "3.7"
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "9229:9229"
    command: "nodemon --inspect=0.0.0.0:9229 src/index.js --watch src"
