version: "3.7"
services:
  jsls:
    build: .
    volumes:
      - ${PROJECT_PATH}:${PROJECT_PATH}
    working_dir: ${PROJECT_PATH}
    ports:
      - "2089:2089"
    command: "javascript-typescript-langserver -p 2089"
    init: true
