---
version: '3'
services:
  firebase:
    build: .
    volumes:
      # - ~/path/to/app:/code
      - firebase-config:/home/firebase/.config
    working_dir: "/code"
    ports:
      - 9005:9005 # firebase login
      - 5000:5000 # hosting
      - 5001:5001 # functions
volumes:
  firebase-config:
