version: "3.7"
services:
  python3:
    image: python:3.10
    volumes:
      - cache:/cache
      - "${PROJECT_PATH:-./project}:/project"
    working_dir: /project
    ports:
    - "18000:18000"
    - "18001:18001"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PROJECT_PATH
    init: true
volumes:
  cache:
