version: "3.7"
services:
  python3:
    image: python:3.7
    volumes:
      - cache:/cache
      - "${PROJECT_PATH:-./project}:/project"
    working_dir: /project
    ports:
    - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PROJECT_PATH
    init: true
volumes:
  cache:
