version: "3.7"
services:
  sphinx:
    build: .
    volumes:
      - "${PROJECT_PATH:-./project}:/web"
      - build:/web/_build/html
    ports:
      - "8000:8000"
    working_dir: /web
    command:
      - "sphinx-autobuild"
      - "--port=8000"
      - "--host=0.0.0.0"
      - "--open-browser"
      - "--delay=5"
      - "--ignore='.git'"
      - "--ignore='.#*'" # きいてない？
      - "/web"
      - "/web/_build/html"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PROJECT_PATH
volumes:
  build:
